#<<<<<<< HEAD
# Generated by Django 5.1.1 on 2025-01-07 11:02
#=======
# Generated by Django 5.1.1 on 2025-01-08 10:50
#>>>>>>> v3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_id',
            new_name='student_id',
        ),
    ]
